### ISSUE TITLE
Language in date time picker

### ISSUE THREAD

**Issue by KeaganStevens** [zsmatrix62/echoo.app#42]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Unix Epoch Converter Page'
2. Click on Input labelled by Choose Time
4. See foreign language.

**Expected behaviour**
I would expect it to use my local operating system language.

**Screenshots**
![echo_langaufge_bug](https://user-images.githubusercontent.com/47221204/187049559-07bcd8ed-019c-4583-8cf9-ac9a368536b5.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.28.0

**Additional context**
My operating system's language is English(US)

**Comment by zsmatrix62** [comment]
Hi @KeaganStevens - Thanks for your heads-up for the widget i18n issue, as we're not making an application wide translation it's temporarily set to English as default. It has been patched in v0.28.1, you will receive a release on next major version update or you can build your own from source code.
