### ISSUE TITLE
Windows Build for v0.29.0 is Missing.

### ISSUE THREAD

**Issue by skj-skj** [zsmatrix62/echoo.app#56]
Hi, @zsmatrix62 thx for this app. if possible can u please add windows build for the latest version.

**Comment by skj-skj** [comment]
is this project still active?

**Comment by zsmatrix62** [comment]
> is this project still active?

Current version is a fail taste of react+tauri, I'm currently working on to release of V1 by using angular, please check at thsi preview: [https://v1.web.echoo.app](https://v1.web.echoo.app)
